//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.VMS.MODEL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_CONTRACTOR
    {
        public MAS_CONTRACTOR()
        {
            this.TRN_PROJECT_MASTER = new HashSet<TRN_PROJECT_MASTER>();
        }
    
        public int AUTO_ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string TEL { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual ICollection<TRN_PROJECT_MASTER> TRN_PROJECT_MASTER { get; set; }
    }
}
