//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.VMS.MODEL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_PROJECT_MEMBER
    {
        public int AUTO_ID { get; set; }
        public int PROJECT_ID { get; set; }
        public string CARD_TYPE { get; set; }
        public string ID_CARD { get; set; }
        public string FULLNAME { get; set; }
        public string POSITION { get; set; }
        public string SAFETY_TRAINING_FLAG { get; set; }
        public Nullable<System.DateTime> TRAINING_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> TRAINING_EXPIRE_DATE { get; set; }
    
        public virtual TRN_PROJECT_MASTER TRN_PROJECT_MASTER { get; set; }
    }
}
