//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.VMS.MODEL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_CUSTOMER_VISIT_LIST
    {
        public int AUTO_ID { get; set; }
        public int CUSTOMER_VISIT_ID { get; set; }
        public int SEQ { get; set; }
        public string FULLNAME { get; set; }
    
        public virtual TRN_CUSTOMER_VISIT TRN_CUSTOMER_VISIT { get; set; }
    }
}
