//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.VMS.MODEL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_CUSTOMER_VISIT_PURPOSE
    {
        public int AUTO_ID { get; set; }
        public int CUSTOMER_VISIT_ID { get; set; }
        public int SEQ { get; set; }
        public string PURPOSE_TYPE { get; set; }
        public string DISCUSSION_PLACE { get; set; }
        public string DISCUSSION_ACK_BY { get; set; }
        public Nullable<System.DateTime> DISCUSSION_ACK_DATE { get; set; }
        public string DISCUSSION_APP_BY { get; set; }
        public Nullable<System.DateTime> DISCUSSION_APP_DATE { get; set; }
        public string DISCUSSION_FINAL_APP_BY { get; set; }
        public Nullable<System.DateTime> DISCUSSION_FINAL_APP_DATE { get; set; }
        public string PURCHASING_PLACE { get; set; }
        public string PURCHASING_AREA { get; set; }
        public string PURCHASING_REF_DOC_NO { get; set; }
        public string PURCHASING_APP_BY { get; set; }
        public Nullable<System.DateTime> PURCHASING_APP_DATE { get; set; }
        public string PLANT_TOUR_AREA { get; set; }
        public string PLANT_TOUR_BY { get; set; }
        public Nullable<System.DateTime> PLANT_TOUR_DATE { get; set; }
        public string PLANT_TOUR_APP_BY { get; set; }
        public Nullable<System.DateTime> PLANT_TOUR_APP_DATE { get; set; }
        public string PLANT_TOUR_FINAL_APP_BY { get; set; }
        public Nullable<System.DateTime> PLANT_TOUR_FINAL_APP_DATE { get; set; }
    
        public virtual TRN_CUSTOMER_VISIT TRN_CUSTOMER_VISIT { get; set; }
    }
}
